import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Menu from './menu'
import ThemeRegistry from './_theme/theme.registory'
import { AuthContext, AuthContextProvider } from './account/AuthContext'
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import "@fortawesome/fontawesome-free/css/all.min.css"
import React, { useContext } from 'react'
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function Icon() {
  const router = useRouter();
  const authContext = useContext(AuthContext);

  const sss = {
    display: 'flex',
    paddingBottom: '5px'
  };

  const ssss = {
    paddingTop: '12px',
    paddingLeft: '12px'
  };

  const sssss = {
    paddingTop: '12px',
  };

  if (authContext && authContext.displayName !== "") {
    if (authContext && authContext.displayName === "普通") {
      return (
        <div style={sss}>
          <i className="fas fa-circle-user fa-3x" onClick={() => router.push("/account")}></i>
          <h5 style={sssss}>使用者 {authContext.email}，您好</h5>
        </div>
      );
    } else {
      return (
        <div style={sss}>
          <i className="fas fa-circle-user fa-3x" onClick={() => router.push("/account")}></i>
          <h5 style={ssss}>商家 {authContext.displayName} , 您好</h5>
        </div>
      );
    }
  } else {
    return (
      <div style={sss}>
        <i className="fas fa-circle-user fa-3x" onClick={() => router.push("/account")}></i>
        <h5 style={ssss}>登入/註冊</h5>
      </div>
    );
  }

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const sss = {
    display: 'flex',
    paddingTop: '17px',
    paddingLeft: '17px',
    backgroundColor: '#FF95CA'

  }

  const icon = {
    paddingLeft: '60%'

  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={sss}>
          <h1>輔仁大學學餐菜單</h1>
          <div style={icon}>
            <AuthContextProvider>
              <Icon />
            </AuthContextProvider>
          </div>
        </div>
        <ThemeRegistry>
          <AuthContextProvider>
            <Menu />
            {children}
          </AuthContextProvider>
        </ThemeRegistry>
      </body>

    </html>
  )
}
